#!/bin/bash
# Run once with the keypad plugged in.
# Detects the keypad's USB vendor/product ID and writes a udev rule
# that grants the input group access to ONLY that device.
RULE_FILE=/etc/udev/rules.d/99-nursery-keypad.rules

echo "==> Looking for a keypad with KEY_F13 capability..."

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
VENV_PYTHON="$SCRIPT_DIR/venv/bin/python"
if [ ! -x "$VENV_PYTHON" ]; then
    echo "ERROR: venv not found at $SCRIPT_DIR/venv. Run install.sh first."
    exit 1
fi

KEYPAD_PATH=$("$VENV_PYTHON" - <<'PYEOF'
import sys
try:
    import evdev
except ImportError:
    print("ERROR: evdev not installed. Run install.sh first.", file=sys.stderr)
    sys.exit(1)

for path in evdev.list_devices():
    try:
        dev = evdev.InputDevice(path)
        name = dev.name.lower()
        if "sayodevice" in name and "keyboard" in name:
            print(path)
            sys.exit(0)
    except Exception:
        pass
# print nothing on failure — bash checks for empty output
PYEOF
)

if [ -z "$KEYPAD_PATH" ]; then
    echo "ERROR: No SayoDevice keypad found."
    echo "       Make sure the keypad is plugged into the Pi."
    exit 1
fi

echo "    Found: $KEYPAD_PATH"

# Resolve the sysfs path for this event device to get USB attributes
SYS_PATH=$(udevadm info --query=path --name="$KEYPAD_PATH" 2>/dev/null)
if [ -z "$SYS_PATH" ]; then
    echo "ERROR: Could not get sysfs path for $KEYPAD_PATH"
    exit 1
fi

# Walk up the sysfs tree to find the USB device with idVendor/idProduct
VENDOR=""
PRODUCT=""
CHECK="$SYS_PATH"
while [ -n "$CHECK" ] && [ "$CHECK" != "/" ]; do
    V=$(cat "/sys${CHECK}/idVendor" 2>/dev/null || true)
    P=$(cat "/sys${CHECK}/idProduct" 2>/dev/null || true)
    if [ -n "$V" ] && [ -n "$P" ]; then
        VENDOR="$V"
        PRODUCT="$P"
        break
    fi
    CHECK=$(dirname "$CHECK")
done

if [ -z "$VENDOR" ] || [ -z "$PRODUCT" ]; then
    echo "ERROR: Could not determine USB vendor/product ID."
    echo "       Try running: lsusb   and identify your keypad manually."
    exit 1
fi

echo "    Vendor ID:  $VENDOR"
echo "    Product ID: $PRODUCT"

echo "==> Writing scoped udev rule to $RULE_FILE ..."
sudo tee "$RULE_FILE" > /dev/null <<EOF
# Nursery keypad — scoped to vendor $VENDOR, product $PRODUCT only.
# Generated by setup_udev.sh. Safe to regenerate any time.
SUBSYSTEM=="input", ATTRS{idVendor}=="$VENDOR", ATTRS{idProduct}=="$PRODUCT", GROUP="input", MODE="0660"
EOF

sudo udevadm control --reload-rules
sudo udevadm trigger

echo ""
echo "==> udev rule installed. Unplug and replug the keypad, then run:"
echo "    bash find_device.sh"
